/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_tenpercent_ndkopengles2triangle_NativeWrapper */

#ifndef _Included_com_example_tenpercent_ndkopengles2triangle_NativeWrapper
#define _Included_com_example_tenpercent_ndkopengles2triangle_NativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_tenpercent_ndkopengles2triangle_NativeWrapper
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_tenpercent_ndkopengles2triangle_NativeWrapper_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_example_tenpercent_ndkopengles2triangle_NativeWrapper
 * Method:    nativeResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_tenpercent_ndkopengles2triangle_NativeWrapper_nativeResize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_tenpercent_ndkopengles2triangle_NativeWrapper
 * Method:    nativeDraw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_tenpercent_ndkopengles2triangle_NativeWrapper_nativeDraw
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
